In [1]:
import pandas as pd
import numpy as np
import urllib.request, json

Set optional print display

In [2]:
pd.set_option("display.max_rows", 100)  # Show up to 100 rows
pd.set_option("display.max_columns", 50)

In [3]:
URL = 'https://script.google.com/macros/s/AKfycbwEg8etJeR1plrJVqakH0nu7oZoXAVe6EIRbJPWKl3nLvzOh-tXtsGoVwZeo1WPqS7ffw/exec'

Run script and get json from API endpoint

In [4]:
raw_data = {}
with urllib.request.urlopen(URL) as data_url:
    raw_data = json.load(data_url)

In [5]:
assert raw_data['data']

In [6]:
def rawToDf(raw):
    data = raw['data']
    df = pd.DataFrame(data[1:], columns=data[0])
    return df

In [7]:
df = rawToDf(raw_data)

In [8]:
df

,Date,Hours ($2),Overtime ($3),cece,kira,"mili 2nd, lola, & other models",Total Sales,Earnings Model 1,Earnings Model 2,Earnings Model 3,Total Earnings,Pay Period Earnings,Pay Date
0,2024-01-01T05:00:00.000Z,,,,,,0,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
1,2024-01-02T05:00:00.000Z,,1,,,,0,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
2,2024-01-03T05:00:00.000Z,,,,,,0,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
3,2024-01-04T05:00:00.000Z,,,,,,0,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
4,2024-01-05T05:00:00.000Z,,,,,,0,#ERROR!,#ERROR!,#ERROR!,#ERROR!,#ERROR!,January 12th
5,2024-01-06T05:00:00.000Z,8,,,,333,333,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
6,2024-01-07T05:00:00.000Z,8,,,,122,122,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
7,2024-01-08T05:00:00.000Z,8,,,,215,215,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
8,2024-01-09T05:00:00.000Z,8,,,16,198,214,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
9,2024-01-10T05:00:00.000Z,8,,125,23,126,274,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
10,2024-01-11T05:00:00.000Z,,,56,,,56,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
11,2024-01-12T05:00:00.000Z,8,,,,147,147,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
12,2024-01-13T05:00:00.000Z,,,,,,0,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
13,2024-01-14T05:00:00.000Z,8,,23,,215,238,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
14,2024-01-15T05:00:00.000Z,8,,,,118,118,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
15,2024-01-16T05:00:00.000Z,8,,,,454,454,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
16,2024-01-17T05:00:00.000Z,8,1,62,,278,340,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
17,2024-01-18T05:00:00.000Z,,8,289,,220,509,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
18,2024-01-19T05:00:00.000Z,8,,,,278,278,#ERROR!,#ERROR!,#ERROR!,#ERROR!,#ERROR!,January 26th
19,2024-01-20T05:00:00.000Z,8,,23,,,23,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
20,2024-01-21T05:00:00.000Z,,,,,351,351,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
21,2024-01-22T05:00:00.000Z,8,,,,160,160,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
22,2024-01-23T05:00:00.000Z,6,,,,169,169,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
23,2024-01-24T05:00:00.000Z,,8,,,23,23,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
24,2024-01-25T05:00:00.000Z,,8,,,373,373,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
25,2024-01-26T05:00:00.000Z,8,,,,388,388,#ERROR!,#ERROR!,#ERROR!,#ERROR!,#ERROR!,February 9th
26,2024-01-27T05:00:00.000Z,8,,,,,0,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
27,2024-01-28T05:00:00.000Z,,,,,,0,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
28,2024-01-29T05:00:00.000Z,8,,,,383,383,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
29,2024-01-30T05:00:00.000Z,8,1,,,288,288,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
30,2024-01-31T05:00:00.000Z,,,,,,0,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,
31,Totals,142,27,578,39,4839,2436,#ERROR!,#ERROR!,#ERROR!,#ERROR!,,